### ISSUE TITLE
Regular browser crash

### ISSUE THREAD

**Issue by jodobear** [gab-ai-inc/defiant-browser#1]
## Description 

Been using disserter browser for about 2 weeks now and randomly without any warnings or even unusual resource activity, the browser quietly just shuts down. Before i thought it might be my 20 tabs, but that's not the case. It crashes even with 1 inactive tab. It seems there's like a preset timer at which point it kills itself - over and over. Though when i restart, i can restore my tabs except once when i could not.

## Steps to Reproduce

   1. Start it and leave it running for a couple of days
   2. At one point you will notice it has killed itself.

## Actual result:

Kills itself within 24-72 hours

## Expected result:
Should keep running

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Version 0.67.62 Chromium: 75.0.3770.38 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## System Information:

Linux Mint 19 Tara

**Comment by freespeech4ever** [comment]
Yeah this was my fault... I should not have been using master.  Reverted the download links to 67.13 which didn't have this crash, and will re-base on a stable channel.
