### ISSUE TITLE
xdg-open error

### ISSUE THREAD

**Issue by dln949** [gab-ai-inc/defiant-browser#10]
Dissenter 0.65.121

Ubuntu 18.04.2

When I use Dissenter on Hooktube, and click on a URL link to open another video in the same tab, I get a popup window with this error message:  "Open xdg-open?  Always open these types of links in the associated apps"  The window has two buttons to click on:  "Cancel", and "Open xdg-open".  But, it doesn't matter which one I click, I get the same result:  The window goes away, the desired video does not open at all, and if I click on the video's URL link to try again, the entire same process repeats.  If I click on the link and tell it to open in a new tab, it will.  

I have seen this problem (so far) only on Hooktube.  Here's the strange thing:  No other browser does this.  I do not have this problem with Brave, Chrome, or Firefox.

**Comment by freespeech4ever** [comment]
Does this still happen for you with the latest 66.99?  That is an odd issue, likely related to default app problems, which is not too surprising.. I'd need some help tracking down the problem, don't have a good linux environment for testing, only building.

**Comment by dln949** [comment]
Now on Dissenter 66.100, still the same problem.

**Comment by freespeech4ever** [comment]
Please check in on this when 68.131 is released and re-open if there are still linux issues. thanks!

**Comment by dln949** [comment]
Still the same problem on version 68.132.
