### ISSUE TITLE
blocking cookies doesn't work

### ISSUE THREAD

**Issue by BrandonSmith22** [gab-ai-inc/defiant-browser#14]
## Description 
If I use the`dissenter://settings/content/cookies` and attempt to block cookies from e.g. Youtube, using the filter `[*.]youtube.com`, Youtube is still able to insert cookies when I visit Youtube.com

## Steps to Reproduce

in `dissenter://settings/content/cookies` 

   1. Clear all youtube cookies
   2. enter the cookie block filter `[*.]youtube.com`
   3. in a separate tab, open youtube.com and start a video
   4. Examine your cookies.  You will see cookies for youtube.com (usually three) 

## Actual result:
A site that matches the "block cookies" setting is still allowed to set cookies.

## Expected result:
A site whose cookies are blocked should not be able to set cookies.

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)  (OSX)

## Other Additional Information:
I was able to reproduce this on the latest version of Brave

**Comment by freespeech4ever** [comment]
Since this exists in upstream, I'll close this.  Please open an issue on their repo 😃
