### ISSUE TITLE
Ads not being blocked

### ISSUE THREAD

**Issue by hoggatt** [gab-ai-inc/defiant-browser#15]
## Description 

The Dissenter browser is not blocking ads for me. This seems very strange. 

## Steps to Reproduce

   1. Go to the following website: https://ads-blocker.com/testing/
   2. See that there are ads when the shields are up

## Actual result:
![ads](https://user-images.githubusercontent.com/37279082/61385271-ae476580-a877-11e9-8e54-8bae936988a0.PNG)

## Expected result:
We expect that no ads will appear. I installed 'uBlock' and it blocks ads correctly. 

## Reproduces how often: 

Every ad is shown when only using shields. 

## Brave version (brave://version info)

Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

## Miscellaneous Information:

One thing to note is that I'm using the browser in a corporate environment. I'm actually unable to run Brave with the corporate firewall, but Dissenter works. I don't know why this would lead Dissenter's adblocking not to work, but uBlock's adblocking to work fine.

**Comment by freespeech4ever** [comment]
Can confirm this is a problem... That ad goes away with blocking scripts, but that's not necessary with the current upstream version.  Looking into it.

**Comment by freespeech4ever** [comment]
68.131 will be released shortly, this is verified fixed.  Thanks!
