### ISSUE TITLE
Dissenter browser Won't Update

### ISSUE THREAD

**Issue by scbritton** [gab-ai-inc/defiant-browser#18]
This is a duplicate of https://github.com/gab-ai-inc/defiant-browser/issues/, which was closed.  I think this should be re-opened, either by closing this one and re-opening https://github.com/gab-ai-inc/defiant-browser/issues/7, or by addressing this one.

## Steps to Reproduce

   1. Download the .exe for the latest version of the browser. 
   2. Run the .exe for the latest version of the browser. 
   3. Wait. 

## Actual result:
Nothing happens.  The program seems to end with nothing happening.  The browser does not get updated.

## Expected result:

New browser.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

I have uninstalled the browser and tried running the .exe file with the same result. The only version I can get to work is the installer downloaded from dissenter.com/dist/browser/dissenter-browser-0-66-99.exe, which installs 0.66.49 again.

**Comment by freespeech4ever** [comment]
Make sure you *close* the running dissenter browser before running the upgrader.  Unfortunately, right now we're just using & providing the "mini_installer" that Chromium uses... It's not the smartest thing.  It would be nice when we get time, to make a proper installer.
