### ISSUE TITLE
option to disable/remove dissenter extension?

### ISSUE THREAD

**Issue by xDevagya** [gab-ai-inc/defiant-browser#2]
is it possible to remove the extension or build the browser without dissenter extension?

**Comment by freespeech4ever** [comment]
The hackiest way is probably to remove the extension id from the whitelist, then it would fail to ever load the extension.  I'm not sure why we'd want to enable that, but would consider a PR that added it, and will leave this issue open to collect any other interest.

**Comment by ZebulanStanphill** [comment]
I think there should at least be an option to hide the Dissenter comments button from the UI, similar to how Brave lets you hide the Brave Rewards button.

**Comment by aeonBTC** [comment]
Yes please allow an option to uninstall the dissenter extension. This is a great web browser but not everyone wants to use unnecessary extensions. Please stand for user choice on this front.

**Comment by freespeech4ever** [comment]
We thought about it and talked about it.. Don't see any reason to hide the dissenter action, it's the dissenter browser.  The analogy to me isn't that rewards can be hidden, it's that Shields can't be.
