### ISSUE TITLE
How to contribute to gab-social?

### ISSUE THREAD

**Issue by Parvith** [gab-ai-inc/defiant-browser#20]
Sorry for using the wrong channel, but I don't know how (if at all) to reach out to your git lab. I've found a bug with gab.com, and I see you have a gitlab at https://code.gab.com/gab/social/gab-social, but I don't see any way to fork or make a PR. Is that code also open to community contribution?

**Comment by freespeech4ever** [comment]
I found some info on that here, looks like you should open an issue on the gitlab: https://code.gab.com/gab/social/gab-social/blob/develop/CONTRIBUTING.md

**Comment by ZebulanStanphill** [comment]
@freespeech4ever That's not possible, because you can't sign up for an account on your GitLab instance. There is only an option to sign in, which is useless if you don't already have an account. And if you can't get an account in the first place... how can you sign in?

**Comment by freespeech4ever** [comment]
@ZebulanStanphill ah, i see.. I'm not involved in the gab-social project, try connecting with "a" on gab or "getongab" on Twitter and asking for access.
