### ISSUE TITLE
Where is the feed stored?

### ISSUE THREAD

**Issue by ghost** [gab-ai-inc/defiant-browser#21]
I searched for the issue.  Attempting to identify where in the source code the URL stream for the Home/Across the Web selections are stored.

**Comment by freespeech4ever** [comment]
In the browser it would be in the defiant-core repo: https://github.com/gab-ai-inc/defiant-core/tree/dissenter-68.x/components/dissenter_extension/extension/dissenter_extension

That is coming from the browser extension though, which is here: https://github.com/gab-ai-inc/gab-dissenter-extension

a version is built / modified / embedded with the browser.
