### ISSUE TITLE
Crash on new tab (usually on cloudflare pages)

### ISSUE THREAD

**Issue by phanomgames** [gab-ai-inc/defiant-browser#22]
The browser tabs close when opening links in new tabs. Copying the url and manually pasting it at the top works fine. I've noticed this more on pages protected by cloudflare. After you're cloudflare authorized (passed the auto check) it works fine for around the next 24 hours.

I reproduced this on 2 computers and a clean VM

## Steps to Reproduce

   1. open a url protected bycloudflare with control left click or right click > open in new tab
   2. wait 6~ seconds for the tab to auto close (don't navigate to it)

## Actual result:
Tab closes automatically (I'm assuming cloudflare doesn't like it?)

## Expected result:
Page opens fine in brave/chrome.

## Reproduces how often: 
Everytime a cloudflare page tries doing its automated validation.

## Brave version (brave://version info)
Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

## Version/Channel Information:
Can reproduce in current release.

## Other Additional Information:
Can't be reproduced in the latest chrome.

**Comment by freespeech4ever** [comment]
Really strange behavior... Just finishing up a very large overhaul of how we build the browser... please test this on 68.131 which comes out shortly.

**Comment by phanomgames** [comment]
Trying to run the dissenter update brings me to "https://www.dissenter.com/download" which 404's. Going to re-download it manually

*Edit* actually, it says update available, but the site still only has .66 https://dissenter.com/#download

**Comment by phanomgames** [comment]
This was fixed at some point. Hasn't happened since a few updates ago.
