### ISSUE TITLE
Add a way to access Dissenter comment extension settings

### ISSUE THREAD

**Issue by ZebulanStanphill** [gab-ai-inc/defiant-browser#3]
## Description 
When the Dissenter browser extension is installed in a browser like Chromium or Brave, there is a way (albeit a little buried) to find the extension settings for things like toggling whether to show the comment count badge.

Somewhat ironically, however, these options are not surfaced in the Dissenter browser. The Dissenter extension does not appear in the Extensions page, and the options are not included in the primary Settings page. The only way to access the Dissenter extension settings is via direct link: chrome-extension://komainihbiaopejdcakhjbjmglkcfhgb/options/options.html

I think the Dissenter comment extension settings should be surfaced on the primary Settings page, since the extension is built in to the browser, similar to how the Shields settings are surfaced.

## Dissenter version
Version 0.67.13 Chromium: 74.0.3729.131 (Official Build) (64-bit)

**Comment by freespeech4ever** [comment]
Coming in the next release:

![dissenter-settings](https://user-images.githubusercontent.com/50223172/59144091-296b5100-8987-11e9-89ab-96ad21c07e71.png)

Can also add a way to get there from the regular settings screens.

**Comment by gfosco** [comment]
Shipped in 65.118, downloadable from dissenter.com

**Comment by freespeech4ever** [comment]
Shipped in 65.118
