### ISSUE TITLE
"Chocolatey" package needs upgrading / additional maintainers

### ISSUE THREAD

**Issue by NohbdyAhtall** [gab-ai-inc/defiant-browser#40]
Truly forgive me for the low-effort and de-templatized issue(beginner GitHubber), but I think it might be simple:

**Chocolatey** is a package manager for Windows, as you may know. Dissenter is the first package I've come across that is quite **out-of-date**.
Here is the listing: https://chocolatey.org/packages/dissenter-browser

There appears to be one maintainer, so I was thinking maybe one of you here could slip in there for backup? It honestly looks like the only thing needing updating is a string in a `.ps1` file to point to the newest version, instead of that particular one. (If there is a way to supply a URL for "get latest version's EXE", then maybe it could be a one-time change?)

Link to Chocolatey's info on requesting to be a maintainer: https://chocolatey.org/docs/package-triage-process
Link to contributor(Chocolatey site): https://chocolatey.org/profiles/swarns
Link to contributor(GitHub, package for choco): https://github.com/0x737761726e73
Link to file in question: https://github.com/0x737761726e73/choco/blob/master/dissenter-browser/tools/chocolateyinstall.ps1

**Comment by freespeech4ever** [comment]
I'm not sure I will get around to this, but it would be cool if someone else maintained it. :)
