### ISSUE TITLE
Will you provide .deb or rpm packages anymore?

### ISSUE THREAD

**Issue by realChytraeus** [gab-ai-inc/defiant-browser#45]
## Description 
Will you provide .deb or rpm packages anymore? I provide a script for Slackware users that repackages the rpm into a Slackware package. https://slackbuilds.org/repository/14.2/network/dissenter-browser/?search=dissenter

**Comment by freespeech4ever** [comment]
Yeah, will have a linux update pretty soon.

**Comment by realChytraeus** [comment]
Great! thank you.

**Comment by realChytraeus** [comment]
Will you still be releasing a linux rpm or deb package?
