### ISSUE TITLE
Installing extensions from Chrome Web Store always fails

### ISSUE THREAD

**Issue by ZebulanStanphill** [gab-ai-inc/defiant-browser#5]
## Description 
I installed Dissenter browser 65.118 on a 64-bit Windows 10 device. When I tried to install an extension from the Chrome Web Store, it failed.

On another device running Linux, I had the same issue. Installing extensions worked on the 67.x version I was using before, but it no longer worked in 65.118. So this bug is a regression.

![image](https://user-images.githubusercontent.com/19592990/59295753-1045f700-8c4a-11e9-8b07-366eb2c41a61.png)

## Steps to Reproduce
1. Install the Dissenter browser 65.118 on Windows 10 or Linux. (I haven't tested macOS.)
2. Go to an extension page in the Chrome Web Store, e.g. https://chrome.google.com/webstore/detail/dissenter-blue-extension/hbbckjcgcpfmplkmdpflmjbloahcakii
3. Try installing the extension.

## Dissenter version (dissenter://version info)
0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)

**Comment by collincusce** [comment]
Ditto. Trying to enable IPFS in the Get Started page and saw this as well.

**Comment by freespeech4ever** [comment]
Compared network_constants.cc to the previous tree.. I had black-holed another brave address in network_constants.cc.  Before this project I'd never touched Chromium, so I'm missing a lot of context as to why the chrome extension store, which hosts the extension downloads, would be creating a URL based on data from the browser... I'll look in to what purpose this serves (beyond giving Brave data on what extensions you're installing.) url is: go-updater.brave.com/extensions in common/network_constants.cc.  Patching it now, it will be in the next binary.

**Comment by freespeech4ever** [comment]
https://github.com/gab-ai-inc/defiant-core/blob/65.118/browser/net/brave_common_static_redirect_network_delegate_helper.cc#L40

Look at that... the browser detects a chrome web store URL and replaces it.  

Patch is to just disable that function, return net::OK immediately.

**Comment by freespeech4ever** [comment]
Fixed here: https://github.com/gab-ai-inc/defiant-core/commit/9f273710501e48cc07948280943131c16a787029

Will keep this open for visibility until the next binary is ready for download.

**Comment by collincusce** [comment]
Request that you build test cases for this. Not being able to install LastPass is an adoption blocker.

**Comment by freespeech4ever** [comment]
Yeah, definitely, I should've tested it more, was just excited to get the new version out.

**Comment by ZebulanStanphill** [comment]
Thank you for your hard work, @freespeech4ever!

**Comment by freespeech4ever** [comment]
Fixed in 65.120
