### ISSUE TITLE
Broken login for website

### ISSUE THREAD

**Issue by jasin** [gab-ai-inc/defiant-browser#6]
Broken login for my website built on golang/beego that uses sessions based on cookie data. Doesn't matter if I disable shield or not, **the verification works, but the session information is not being read properly even when the cookie  sessionID exist.** Works in brave with shield up but broken in dissenter. Cookie data **exist** in both Dissenter and Brave. 

**Expected Result:** the browser should provide the cookie data in a GET request to the server.
the cookie data is quite simple, it provides a session ID that the server can use to locate the session data for said(SessionID) provided by the browser.

At the very least I'd expect this to work with the Dissenter shield down for said website. 

I'd be willing to share information if requested.

**Comment by freespeech4ever** [comment]
We aren't changing anything that should affect this in Dissenter.  Try the latest build, 65.121 (you may have been on the less-stable 67.x channel that we worked on previously).  Let me know if you still have an issue.
