### ISSUE TITLE
Dissenter refuses to update to latest version

### ISSUE THREAD

**Issue by nolsen42** [gab-ai-inc/defiant-browser#7]
Running V0.67.62 (Windows 10, 64-bit), trying to update to the latest. I tried two methods into updating it, but nothing happens.

Steps taken:
1. Download latest version.
2. run .exe
3. Wait...
4. Launch Dissenter, version is still 0.67.62.

I also tried closing dissenter completely before running update, nothing happens either.
Looking at task manager, it does run, but it closes after a few seconds.

![image](https://user-images.githubusercontent.com/7462688/59951963-df2ea900-9437-11e9-8d7e-54578d712d41.png)

After a few seconds, this will close and the update appears to be a failure.
Updating this method worked before, up until the downgrade to 0.65*.

**Comment by freespeech4ever** [comment]
Odd.  Try uninstalling.. hit the windows key and start typing remove.  Pick add/ remove programs and uninstall dissenter.

**Comment by nolsen42** [comment]
Will this delete my browsing history/cookies/cache as well as all my user data?

**Comment by freespeech4ever** [comment]
Yes.   You could try making a copy of c:\users\yourname\appdata\local\GabAI and put it back after uninstall tho.

**Comment by freespeech4ever** [comment]
Just released 65.121, which is now code-signed on windows.  Hope you're able to resolve your issue with upgrading, haven't seen this behavior elsewhere (yet).  Check the location of what you're launching, the properties of the shortcut, make sure you don't have a separate/old version somewhere else?  I did see that on a development machine once.

**Comment by scbritton** [comment]
This issue should be re-opened, as I am experiencing the same problem:  Download the .exe for the latest version of the browser.  Run the .exe for the latest version of the browser.  Wait.  Nothing happens.

I have uninstalled the browser and tried running the .exe file with the same result.  The only version I can get to work is the installer downloaded from dissenter.com/dist/browser/dissenter-browser-0-66-99.exe, which installs 0.66.49 again.  

So there is a serious installation issue somewhere.

**Comment by nolsen42** [comment]
There should be a error message at least, and not die in the background with no clue why.
