### ISSUE TITLE
Unexpected behavior for middle clicking a tab.  Browser window moves instead of tab closing.

### ISSUE THREAD

**Issue by ScottRFrost** [gab-ai-inc/defiant-browser#8]
## Description 
Unexpected behavior for middle clicking a tab.  Browser window moves instead of tab closing.

## Steps to Reproduce
   1. Open multiple tabs
   2. Middle click one you don't want anymore

## Actual result:
Browser bizarrely moves the entire window to the right.

## Expected result:
Browser doesn't move, tab closes

## Reproduces how often: 
Trivial to reproduce

## Version/Channel Information:
Version 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)

## Related Reddit question
https://www.reddit.com/r/Dissenter/comments/c4vu8x/in_dissenter_browser_is_there_any_way_to_get/

**Comment by freespeech4ever** [comment]
Looks related to this: https://github.com/electron/electron/issues/18978

**Comment by ScottRFrost** [comment]
Tested working in version **0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)** even though the linked upstream bug is still open.  Middle clicking a tab now correctly closes the tab.
