### ISSUE TITLE
Linux WM_CLASS is Wrong

### ISSUE THREAD

**Issue by tbsteinb** [gab-ai-inc/defiant-browser#9]
## Description 
The WM_CLASS on Linux is currently `brave-browser`. The issue with this is it screws up the icon for the browser on desktop environments such as Gnome. In my case, I had Brave installed as well, and while the launch icon was right, once the app was running it was actually using Brave's icon. This made it so if I had dissenter marked as a favorite on my dash I would have an extra icon while running.

## Steps to Reproduce

   1. Use a desktop environment like Gnome
   2. Launch Dissenter Web Browser
   3. Look at the dash and see two icons are present

## Actual result:
There are 2 icons present. If you would like a screen shot, let me know and I'll revert the changes I made and post one.

## Expected result:
There should only be 1 icon, the one I used to launch it.

## Reproduces how often: 
No steps to reproduce beyond launching it in an environment like Gnome.

## Brave version (brave://version info)
Dissenter: 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)

Revision: 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}

OS: Linux

## Additional Info
A work around until this is changed in the browser itself is to change the Exec lines in dissenter-browser-bin.desktop to have the flag `--class=dissenter-browser` at the end. This should be done for every Exec line.

**Comment by freespeech4ever** [comment]
I used your trick, updating the .desktop file template.  Will be in 66.100.

**Comment by freespeech4ever** [comment]
Re-open if this is still an issue after the coming release 68.131.  Thanks!
